name: sentiment_analysis
channels:
  - conda-forge
dependencies:
  - python=3.8  # Ou la version de Python que tu utilises
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - gensim
  - tensorflow
  - tensorflow-hub
  - transformers
  - ipywidgets
  - wordcloud
  - jupyter
  - pip
  - pip:
    - mlflow  # Si tu utilises MLflow
