name: Deploy Sentiment Analysis API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Create virtual environment
        shell: bash -l {0}
        run: |
          python3 -m venv .venv

      - name: Activate virtual environment and run commands
        shell: bash -l {0}
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          python -m nltk.downloader popular

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest  # Assurez-vous que vos tests sont dans le dossier "tests"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          command_timeout: 20m
          script: |
            cd OC7
            pkill -f "gunicorn.*app:app" || true
            sleep 5
            source .venv/bin/activate
            gunicorn --config gunicorn_config.py app:app &
            sleep 10
            echo "Deployement completed"
