name: Deploy Sentiment Analysis API

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"
          activate-environment: sentiment_analysis_app

      - name: Create conda environment
        shell: bash -l {0}
        run: |
          conda env create -f environment_app.yml

      - name: Initialize conda
        shell: bash -l {0}
        run: |
          conda init bash
          source ~/.bashrc

      - name: Activate conda environment and run commands
        shell: bash -l {0}
        run: |
          conda activate sentiment_analysis_app
          python -m nltk.downloader popular

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd OC7
            sudo systemctl stop gunicorn 
            source /home/ec2-user/miniconda/bin/activate sentiment_analysis_app
            gunicorn --config gunicorn_config.py app:app &

