channels:
- conda-forge
dependencies:
- python=3.8.20
- pip<=24.3.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.1.0
  - numpy==1.24.4
  - packaging==24.2
  - psutil==6.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
